fragment PostParts on Post {
  __typename
  title
  date
  slug
  category
  excerpt
  image
  tags
  servings
  prepTime
  cookTime
  totalTime
  ingredients
  ingredientSections {
    __typename
    title
    items
  }
  instructions
  instructionSections {
    __typename
    title
    steps
  }
  nutrition {
    __typename
    calories
    protein
    carbs
    fat
    fiber
    sugar
  }
  body
}
